### ISSUE TITLE
parse with error_code

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#11]
`view::view( string_view s, error_code& ec)`

and

`basic_value::basic_value( string_view s, error_code& ec )`

can leave the URL empty on error

**Comment by syoliver** [comment]
@vinniefalco Your url implementation is really interesting, but would you think possible to have a separate function for parsing urls or maybe something like a named constructor ?
I think it would improve readability.

**Comment by vinniefalco** [comment]
Yeah, I will have that eventually, mind you that this library is still being worked on (I'm busy with Boost.JSON at the moment: https://github.com/CPPAlliance/json

Thanks!

**Comment by syoliver** [comment]
Yes I know about json library, but I would like to help on url if possible, without conflicting with what you have already done or what you have in mind.
This issue seems easy to begin with and try to propose something.

**Comment by edtanous** [comment]
+1  Those two prototypes would be very useful for codebases with -fno-exceptions set.  I tried to integrate this library into something I've been working on and the inability to capture an error in control flow when translating an unverified target string to a url is about the only thing holding me back from being able to use this in my use.  For the golden paths, this library seems to work fantastically as intended.

**Comment by vinniefalco** [comment]
> the inability to capture an error in control flow when translating an unverified target string to a url is about the only thing holding me back from being able to use this in my use

This should be completely fixed now, there's a full suite of parse functions which use errors. Furthermore, you can manipulate URLs without any memory allocations using `static_url`.
