### ISSUE TITLE
Modifiable query parameters

### ISSUE THREAD

**Issue by dgrr** [CPPAlliance/url#14]
Hello,

I notice the function `params` is only able to return a read-only `params_type` class holding the query parameters. Is it possible to implement a version with modifiable parameters?

Thanks.

**Comment by vinniefalco** [comment]
Yes, it is planned (and same for path)

**Comment by dgrr** [comment]
Ok. I'd like to accelerate that process. How do you want to implement that? Creating a class like `url_view` but modifiable?
I can try to do a PR.

**Comment by vinniefalco** [comment]
> I can try to do a PR.

Unfortunately you will simply have to wait. This project is not yet in beta and I am working on other things. The way to do it is to add the mutating functions to `url_base::params_type`:
https://github.com/CPPAlliance/url/blob/develop/include/boost/url/url_base.hpp#L86

**Comment by vinniefalco** [comment]
This is being worked on now
