### ISSUE TITLE
build tables for url

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#146]
URL does not build or use the lookup tables. It needs to do both. It might be worth looking into pushing the copied strings logic deeper into the implementation first.

**Comment by alandefreitas** [comment]
@vinniefalco do you have a reference of the pattern you would like for the lookup tables? Something from boost.json, maybe? Or only a vector allocated with `const_string::factory` allocator? Some small vector buffer would also be helpful.

**Comment by vinniefalco** [comment]
http-proto handles the tables correctly, we should model the implementation based on that: 

https://github.com/CPPAlliance/http_proto/blob/be4c4935515462119d14830cbba7ed1a3ed615d9/include/boost/http_proto/detail/fields_table.hpp#L30

**Comment by alandefreitas** [comment]
OK. Great!

**Comment by alandefreitas** [comment]
Closing this PR as there is not enough user demand at this point.
