### ISSUE TITLE
make segment views bidirectional

### ISSUE THREAD

**Issue by alandefreitas** [CPPAlliance/url#150]
segments has to be BidirectionalRange because users will commonly want quick access to the last segment (i.e. the "filename").

We need to remove the promise of RandomAccess.

**Comment by vinniefalco** [comment]
it would be nice to have `first()` and `last()`

**Comment by alandefreitas** [comment]
I'm not sure about the best design here. `segments_encoded_view::iterator` and `segments_view::iterator` are already bidirectional, but they are constant. Making `segments_encoded::iterator` and `segments::iterator` would just be replicating a lot of that logic. 

Ignoring naming, for now, the only idea I have for not replicating the logic is to get rid of `segments_encoded_view` and `segments_view` (or `segments_encoded` and `segments`) altogether and merge their logic into only two containers. The two containers left would have the non-const functions and act as any other STL container with two kinds of iterators: `iterator` and `const_iterator`, all with the current logic of `segments_encoded_view::iterator` and `segments_view::iterator`.

Is that what we should pursue?

**Comment by vinniefalco** [comment]
No way, leave the containers and just change the iterators

**Comment by vinniefalco** [comment]
`segments_encoded::iterator` is constant as well, no?

**Comment by alandefreitas** [comment]
Should I just replicate the logic from `segments_encoded_view::iterator` into `segments_encoded::iterator` or is there something else?

**Comment by vinniefalco** [comment]
I don't mind making a copy of it, lets get the thing working. We can factor out the increment and decrement algorithms into separate functions if we want, to share the code.

**Comment by alandefreitas** [comment]
`segments_encoded::iterator` and `segments_encoded_view::iterator` are both constant. This PR is going to be equivalent to copy-pasting all the logic from `segments_encoded_view::iterator` into `segments_encoded::iterator`.

**Comment by alandefreitas** [comment]
> I don't mind making a copy of it, lets get the thing working. We can factor out the increment and decrement algorithms into separate functions if we want, to share the code.

OK then.
