### ISSUE TITLE
[help] Some questions about this project.

### ISSUE THREAD

**Issue by balusch** [CPPAlliance/url#167]
I'm looking for a modern and efficient URL library(parsing, encoding/decoding...) written in C++ and finally find this project. After reading the readme and some source files, I think it is indeed what I need! However, I also have some questions about it and wish you can help me with them.

- The project name is **Boost.URL**, but it is said not an official sub-project of Boost yet. Will this project be merged into the Boost C++ library in the future?
- Is the project ready to be used in the production evnrionment now, or still in early development?
- My project is using Boost as a third-party depencency, and is there any way to build this project with such an external Boost library?
- After skimming the CMakeLists.txt I found that it requires Boost-1.78.0, which is almost the newest version. Does it really need such a high version? And if not, which version of boost is the miminum requirement of Boost.URL?

Thanks in advance.

**Comment by sehe** [comment]
(The review process for acceptance into Boost is underway, and can be followed on the Boost mailing list)

**Comment by balusch** [comment]
@sehe Thanks! I'll make a subscription.

**Comment by balusch** [comment]
Hi, @alandefreitas, thanks a lot, it really helps.

> I'm not sure I understand the question. But yes, it depends on Boost, and you can build it with an external recent version of Boost. It has to be a recent version though.

Yes, I just want to known how to build this project together with a Boost already used, or I should wait until it is merged into Boost and use the newest Boost then?

And another concern is the compatibility with Boost of old version. I thought is would be compatible but that seems to be the case according to your following statement. That is a sad thing. 😭

**Comment by alandefreitas** [comment]
> Yes, I just want to known how to build this project together with a Boost already used, 

If you have a *recent* version of Boost installed on your computer, you just need the headers from the `include` directory and then follow the instructions as usual.

> or I should wait until it is merged into Boost and use the newest Boost then?

That's also an option.

> And another concern is the compatibility with Boost of old version. 

Yes. The library isn't even in Boost yet, so only recent versions of Boost.

**Comment by balusch** [comment]
> Yes. The library isn't even in Boost yet, so only recent versions of Boost.

I see. Seems not suitable for our project which is using an older Boost and not easy to update, but I can try it in my new project.

Anyway, thanks to your detailed explanation and such a good project -- URL utility is so fundamental and important in network/backend development.
