### ISSUE TITLE
`const_string` could be NUL-terminated

### ISSUE THREAD

**Issue by sehe** [CPPAlliance/url#168]
If `const_string` guaranteed NUL-termination, some interop would be helped: especially invoking API's that take C-style strings wouldn't require the slightly non-intuitive copy:

```c++
// Set SNI Hostname (many hosts need this to handshake successfully)
if(! SSL_set_tlsext_host_name(stream_.native_handle(), std::string(url.host()).c_str()))
{
```

Not to mention what happens if people forget about the absense, and just use `url.host().data()` naively.

We could make it explicit by providing the `c_str()` accessor (`boost::url::c_str()` already has it).

**Comment by vinniefalco** [comment]
It would have to be via `c_str()`, because `string_view::data()` is not guaranteed to return a null-terminated string.
