### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by kotbegemot** [CPPAlliance/url#17]
Please add a tag.
The tag will help you create a simple conan recipe
@vinniefalco

**Comment by vinniefalco** [comment]
This library is not ready for release

**Comment by kotbegemot** [comment]
We are using it now in the github.com/cyberduckninja/RocketJoe 
Please setup alpha tag.

**Comment by vinniefalco** [comment]
Here you go: https://github.com/CPPAlliance/url/tree/alpha

**Comment by kotbegemot** [comment]
Thanks for the help, we made a recipe https://bintray.com/cyberduckninja/conan/boost-url%3Acyberduckninja.
