### ISSUE TITLE
missing remove_host

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#173]
There's no `url::remove_host`?

**Comment by alandefreitas** [comment]
We cannot remove the host without removing the authority ([`u.remove_authority()`](https://develop.url.cpp.al/url/ref/boost__urls__url/remove_authority.html)).

```
http://user:pass@boost.org:80/users/download
-> 
http://user:pass@:80/users/download
```

This is an empty host ([`set_host("")`](https://develop.url.cpp.al/url/ref/boost__urls__url/set_host.html)) but the host still exists.

**Comment by vinniefalco** [comment]
derrrrrp
