### ISSUE TITLE
Docs: Document minimum Boost requirements

### ISSUE THREAD

**Issue by akrzemi1** [CPPAlliance/url#184]
This library requires Boost 1.78 or higher (e.g., for `result<T>` in Boost.System). Document it in the library's requirements.

Of course, such mention will not make sense once the library is accepted to Boost. But so is the case for the current docs, which say the library "requires Boost."

**Comment by vinniefalco** [comment]
@alandefreitas we need to make sure this is clear if we do any promotion of the library on social media. The repository sholuld be updated to indicate the requirements and pre-Boost-acceptance installation instructions _before_ any campaigns are launched.
