### ISSUE TITLE
Docs: clarify the usage of string_view

### ISSUE THREAD

**Issue by akrzemi1** [CPPAlliance/url#186]
Given the unclear situation in Boost regarding the `string_view`, I think the docs should say that the library uses alias `boost::urls::string_view`, that this alias:

- Is a custom implementation of `std::string_view`'s interface, which works in C++11.
- Is convertible to/from `std::string_view`
- Is an implementation detail of Boost.URL.
- That the namespace and the name of the aliased class may change without notice.

**Comment by vinniefalco** [comment]
See: https://github.com/CPPAlliance/url/issues/190#issuecomment-1148006983
