### ISSUE TITLE
url is semiregular

### ISSUE THREAD

**Issue by akrzemi1** [CPPAlliance/url#194]
https://github.com/CPPAlliance/url/blob/develop/doc/qbk/2.0.quicklook.qbk#L396 says 
> Objects of type [url](https://192.url.prtest.cppalliance.org/libs/url/doc/html/url/ref/boost__urls__url.html) are first-class. They can be copied, moved, and assigned as needed.

The formal name for it is [std::semiregular](https://en.cppreference.com/w/cpp/concepts/semiregular).

**Comment by alandefreitas** [comment]
Why does [std::semiregular](https://en.cppreference.com/w/cpp/concepts/semiregular) imply it can be moved?

**Comment by akrzemi1** [comment]
`std::copyable` implies `std::movable`.
In order to copy in all cases, you need to be able to write:

```c++
T x = std::declval<T>();
```

And this is a move.

**Comment by alandefreitas** [comment]
Oh. I just saw that.

Now I'm not sure a `url` is [std::default_initializable](http://en.cppreference.com/w/cpp/concepts/default_initializable)<T>;

**Comment by alandefreitas** [comment]
Yes. It is. 

```cpp
url() noexcept;
```

wasn't defined before.
