### ISSUE TITLE
static_pool missing inherited javadocs from base class

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#213]
https://master.url.cpp.al/url/ref/boost__urls__static_pool.html

None of the basic_static_pool members are shown?

**Comment by alandefreitas** [comment]
This looks different from #212 in that I can't find the member functions in the Doxygen XML file. But the code also looks fine. I have no idea why this is happening.

**Comment by vinniefalco** [comment]
you might need to open an issue in docca
