### ISSUE TITLE
Documentation error "mailto scheme resource"

### ISSUE THREAD

**Issue by JonKalb** [CPPAlliance/url#214]
The resource for the "mailto" scheme is documented as "Secure WebSocket Protocol" on the "[Scheme](https://master.url.cpp.al/url/parsing/scheme.html)" page.

I do not think is correct.

Perhaps "email address."

**Comment by vinniefalco** [comment]
whoops!

**Comment by alandefreitas** [comment]
Amazing!

Thanks, @JonKalb !
