### ISSUE TITLE
Unnecessary output to stdout during tests

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#247]
There's a bunch of junk being emitted to standard out, which bypasses the unit test stream redirection:
![image](https://user-images.githubusercontent.com/1503976/180908052-06e1e243-f20b-459f-b121-cd5b1cf3871e.png)

**Comment by alandefreitas** [comment]
How should we do these snippets then?

**Comment by vinniefalco** [comment]
Take the address of the function so it ensures that it compiles?
