### ISSUE TITLE
pct_encoding needs a tidying

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#277]
There were functions with the same name, different signatures, in different namespaces. Many call sites are formatted incorrectly and it is unclear which versions of what functions are being called with which arguments. This all needs to be cleaned up, and the boilerplate refactored into a uniquely named set of helper functions as implementation details to cut down on parameter spam and name duplication.

**Comment by alandefreitas** [comment]
> There were functions with the same name, different signatures, in different namespaces. Many call sites are formatted incorrectly and it is unclear which versions of what functions are being called with which arguments. 

I'm not sure I understand this.

**Comment by vinniefalco** [comment]
I had to rename `detail::pct_encode` to `detail::pct_encode_impl` because of ambiguity. Blocks like this are hard to read now:
![image](https://user-images.githubusercontent.com/1503976/182497201-1da95ecf-37eb-423f-91f9-bd81b56077f0.png)

**Comment by vinniefalco** [comment]
also I renamed `detail::pct_encode_bytes` to `detail::pct_encode_bytes_impl` because of conflicts.

**Comment by alandefreitas** [comment]
So you just want to tidy the formatting here or you have something more special in mind?

**Comment by vinniefalco** [comment]
definitely start with a reformatting to be readable
