### ISSUE TITLE
javadoccing hidden friends correctly

### ISSUE THREAD

**Issue by alandefreitas** [CPPAlliance/url#296]
When we write

```cpp
struct T
{
  /** Hey goys!
  */
  friend ostream& operator<<( ostream&, T const & );
};
```

Doxygen does not see this as a global declaration, and thus there is no overload resolution landing page.

This has to be written as

```cpp
struct T
{
  friend ostream& operator<<( ostream&, T const & )
  {
    ...
  }
};

/** Hey goys!
*/
ostream& operator<<( ostream&, T const & );
```

Then Doxygen will see the symbol

**Comment by vinniefalco** [comment]
This commit fixes `operator<<` for `url` and `url_view`:
https://github.com/vinniefalco/url/commit/d26137e927566bdeb8d027ada382865fa7e83cbc

**Comment by vinniefalco** [comment]
merged
