### ISSUE TITLE
url is missing constructors

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#298]
It seems `url` is missing a constructor from string (throwing overload that parses as a URI or relative-ref). `url_view` has the constructor, we can copy from there.

**Comment by alandefreitas** [comment]
This?

https://github.com/CPPAlliance/url/blob/ac3b4e784ed391f55f050042b2b9fc147e0673c0/include/boost/url/url.hpp#L257-L258

**Comment by vinniefalco** [comment]
oh, I missed it? Weird..

**Comment by vinniefalco** [comment]
Please close this if it is not relevant

**Comment by alandefreitas** [comment]
32 issues
