### ISSUE TITLE
Unable to store boost::url in std::any

### ISSUE THREAD

**Issue by ghost** [CPPAlliance/url#36]
I am trying to store a boost::url object inside of an std::any, but receive compilation errors regarding the copy constructor of boost::basic_url, which does not appear to be calling into the boost::url_base constructor properly (I may be interpreting the compiler warnings poorly).

The compilation errors can be seen via the minimal C++ program:

```c++
#include <boost/url.hpp>
#include <iostream>
#include <any>

static constexpr auto github_url = "https://github.com/CPPAlliance/url";

int main()
{
    std::any anything;
    anything.emplace<boost::url>(github_url);
    std::cout << std::any_cast<boost::url&>(anything).encoded_url() << std::endl;
}
```

**Comment by AlexandreBossard** [comment]
I've ran into this myself. The copy/move operators and constructor of `url_base` seems to be the culprit. Anything that require to copy/move a `boost::url` fails.

**Comment by vinniefalco** [comment]
Note that this library is still in development

**Comment by vinniefalco** [comment]
`url` is rewritten to do away with the base, and I've added `static_url`. Copy and move should work, please try it!

**Comment by vinniefalco** [comment]
copy/move pass tests now
