### ISSUE TITLE
Review: using string in `url`

### ISSUE THREAD

**Issue by alandefreitas** [CPPAlliance/url#437]
> In your non-view url object, you seem to allocate storage using
new char[]. Why not use a std::string? One benefit of a std::string
is SBO. Another is that you could provide a move constructor from
a string.

**Comment by vinniefalco** [comment]
if we do this then we can't put a table at the end of the allocation anymore. it has to be thought out. we need to know the benefits versus the costs.

**Comment by alandefreitas** [comment]
> if we do this then we can't put a table at the end of the allocation anymore. 

Yes. Although we're probably not going back to that design.

Not including <string> could be a good reason to avoid it, but this ship has sailed.

> it has to be thought out. we need to know the benefits versus the costs.

I guess the main benefit is SSO/SBO and simpler code. But we can also achieve that if we want.

The move constructor from a string doesn't look like a huge benefit to me. It's technically true though.

**Comment by vinniefalco** [comment]
`std::string` would cause value-initialization on every call to `string::resize`... no thanks.
