### ISSUE TITLE
Review: names of the encoding/decoding views confusing

### ISSUE THREAD

**Issue by alandefreitas** [CPPAlliance/url#438]
> I find the names of the encoding/decoding views confusing. I would
expect a "decoded_view" to refer to underlying encoded data and
return equivalent decoded data when it is read from, but you seen to
call that an "encoded_view".

I agree that some uses might be confusing, like in

```cpp
pct_encoded_view decoded_host = u.host();
```

When we replaced `const_string`, everyone who looked at this view proposed one of  `decode_view`, `decoded_view`, `pct_decoded_view`, or `decoded_view`.

If we follow the convention used in `std::ranges`, then it would be `pct_decode_view`, because it's always a verb:

https://en.cppreference.com/w/cpp/ranges/transform_view
https://en.cppreference.com/w/cpp/ranges#Range_adaptors

**Comment by alandefreitas** [comment]
More comments:

> I do feel that `pct_encoded_view` is an unfortunate choice for a view that
> actively decodes URL-encoded characters. I'd prefer `pct_decode_view` or
> `pct_decoding_view`. Views names should probably  describe the semantics of the
> view itself, not what kind of underlying sequence is being adapted/transformed.

**Comment by alandefreitas** [comment]
More comments:

> I did also find the naming situation for encoded/decoded a bit confusing. In
> particular, url::path returns pct_encoded_view, but url::encoded_path returns
> string_view. I would expect the opposite. Maybe this needs additional
> explanation in the docs?

**Comment by vinniefalco** [comment]
We are going to do `decode_view`
