### ISSUE TITLE
Review: add lowercase/uppercase in pct_encode_opts

### ISSUE THREAD

**Issue by alandefreitas** [CPPAlliance/url#440]
> In the past I have had situations where it was necessary to specify
the case for hex letters in %-encoding; please consider adding this to
pct_encode_opts.

Uppercase should be the default since this is what URL normalization requires.

**Comment by vinniefalco** [comment]
How does the user control whether upper or lowercase is used in the `url_base`?

**Comment by alandefreitas** [comment]
> How does the user control whether upper or lowercase is used in the url_base?

By using `set_encoded_xxxx`. Although they shouldn't be doing that because they would be denormalizing the URL.

**Comment by vinniefalco** [comment]
OK then. Explicit case control is only for percent-encoding free functions.

**Comment by vinniefalco** [comment]
I did this
