### ISSUE TITLE
query_param_encoded_view `noexcept`

### ISSUE THREAD

**Issue by alandefreitas** [CPPAlliance/url#456]
We have many issues here. 

If we want to ensure this is only created by the container, then we need to hide the public constructors that don't validate things. 

If we want to the user to be able to create this, then we need to either validate the input when constructing it or remove `noexcept` from the conversion to the decoded view.

**Comment by vinniefalco** [comment]
Or a third option:

public constructors for the plebs validate and throw, while private constructors for La Cosa Nostra don't validate and are `noexcept`.

**Comment by vinniefalco** [comment]
I believe this is solved with `pct_string_view`.
