### ISSUE TITLE
replace_value is unimplemented

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#59]
It doesn't fit into `edit_params` neatly

**Comment by vinniefalco** [comment]
@alandefreitas if you would like to look at this and propose a solution that would be cool.

**Comment by alandefreitas** [comment]
Could you explain this issue a little better?

**Comment by vinniefalco** [comment]
Member functions in params types

**Comment by vinniefalco** [comment]
https://github.com/CPPAlliance/url/blob/674153089551371eb05901d615c1702e258eadfc/include/boost/url/params.hpp#L518
