### ISSUE TITLE
std::format support

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#62]
> std::format has its own customization mechanism

**Comment by vinniefalco** [comment]
> derive the formatter specialization from the one for string_view and inherit parse from there

**Comment by vinniefalco** [comment]
```
template <> struct std::formatter<muh_type>: std::formatter<std::string_view> {
  // parse is inherited from formatter<string_view>.
  template <typename FormatContext>
  auto format(muh_type const& mt, FormatContext& ctx) {
    return formatter<string_view>::format(mt.get_string_view(), ctx);
  }
};
```

**Comment by alandefreitas** [comment]
`fmt` includes a header `fmt/ostream.h` that supports anything `cout` supports. 
The formatter would be nice but it's not essential to make it work with `fmt`. 

An `operator string_view` probably works with `fmt` too, but including that in tests would require a dependency outside boost.
