### ISSUE TITLE
copied_strings

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#74]
Use copied_strings in every mutating algorithm that needs it

**Comment by alandefreitas** [comment]
Could you explain this issue a little better?

**Comment by vinniefalco** [comment]
Yes, when calling a mutating function (for example in `url`) that takes a `string_view` parameter, and the caller passes a string which is from inside the container. This helper class assists with that:
https://github.com/CPPAlliance/url/blob/674153089551371eb05901d615c1702e258eadfc/include/boost/url/detail/copied_strings.hpp#L19

For example
```
url u = parse_uri( "http://example.com?k1=42&k2=69" );
u.params().emplace_back( "k3", u.params().find( "k2" ).value );
```
