### ISSUE TITLE
URL resolution

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#9]
Algorithms such as resolving a relative-ref to a base URL

**Comment by benstadin** [comment]
FWIW, I'm using a stripped version of the uri parser from Microsofts C++ REST SDK in my Beast based project which does resolve relative paths [1] and query decoding. Just as another reference.  

[1] https://github.com/microsoft/cpprestsdk/blob/cdae258bfb22f948c7b768b4dc56f5f4a2d9b2ce/Release/src/uri/uri.cpp#L437

**Comment by vinniefalco** [comment]
Yep I am going to finish this off this year, I'm currently trying to finish up the string/double conversion in Boost.JSON https://github.com/vinniefalco/json

**Comment by vinniefalco** [comment]
"This year" turned into "2021"

**Comment by vinniefalco** [comment]
This is done, see `resolve`
