### ISSUE TITLE
normalized escaped unreserved characters

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/url#92]
Characters from the unreserved set which are escaped in a URL should have percent-decoding applied during normalization: https://datatracker.ietf.org/doc/html/rfc3986#section-2.3

**Comment by alandefreitas** [comment]
Unless I'm misunderstanding this issue, I think this is already implemented as part of normalization.

**Comment by vinniefalco** [comment]
Is it?

**Comment by alandefreitas** [comment]
Yes. 100%.
